### ISSUE TITLE
Chart view is not displayed

### ISSUE THREAD

**Issue by jhon65496** [Fruchtzwerg94/PlantUmlViewer#12] opened 2023-05-28 19:46 UTC
Chart view is not displayed
I installed the plugin..
Opened the ***.publ** file
Why is there no chart view?

![image](https://github.com/Fruchtzwerg94/PlantUmlViewer/assets/128128859/95f6a35f-e088-4bb4-8d19-36eb80f7f52d)

![image](https://github.com/Fruchtzwerg94/PlantUmlViewer/assets/128128859/6b6aa4fa-be8d-4d27-b4e8-d44c934b54a1)

![image](https://github.com/Fruchtzwerg94/PlantUmlViewer/assets/128128859/b5ecea55-8065-4712-aa22-6bf512fa39c9)

![image](https://github.com/Fruchtzwerg94/PlantUmlViewer/assets/128128859/ed5d2e42-8799-4215-87b3-5cbf963d904c)

**Comment by Fruchtzwerg94** [comment] 2023-05-29 11:04
Hi @jhon65496 ,

- Could you please check if the window may is hidden / tabbed in some other window areas?
- It would be also helpful to see a screenshot of the whole Notepad++ instance
- What is the language you are running on?
- Could you try to update Notepad++ to the latest version to reproduce the issue?

BR, Philipp

**Comment by Fruchtzwerg94** [comment] 2023-06-22 20:15
Closing this issue since it is not reproducible and nor more information was provided.

**Closed** 2023-06-22 20:16 UTC
Labels: bug
