### ISSUE TITLE
Resizing Viewer causing not responding

### ISSUE THREAD

**Issue by BHMath** [Fruchtzwerg94/PlantUmlViewer#11] opened 2023-05-23 08:44 UTC
Description
When I drag the preview window to detach it from the main window it's ok, but as soon as I try to resize it right after npp is not responding. I can't have on one screen my text and on the oter the preview in fullscreen

Solution
npp should not crash

Alternatives
I only keep the preview within the main window

Additional information
Is there any log somewhere I can give you ?
I'm using a Portable version of npp

**Comment by Fruchtzwerg94** [comment] 2023-05-23 10:45
Hi @BHMath ,

definitively not how it should work. Thanks for reporting it.

Which version of the plugin are you using?
Using 1.4.0.8 I am able to see something similar, using the latest build I can't see it.
Sou could you try to reproduce the issue with other versions as well? Especially the [latest build](https://github.com/Fruchtzwerg94/PlantUmlViewer/actions/runs/4408163838)?

BR

**Comment by BHMath** [comment] 2023-05-23 12:07
I forgot to mention the version. I'm using version 1.5.0.9 so the latest i think

**Comment by Fruchtzwerg94** [comment] 2023-05-26 20:11
This seems to be a tricky one since its related to unexpected behaviour in Windows. It is also mentioned [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8723) and affects basically all Notepad++ plugins implemented with .NET and Windows forms.

Anyway, I've found a way to prevent the issue for me, maybe this also works for you.
Please try the [latest build](https://github.com/Fruchtzwerg94/PlantUmlViewer/actions/runs/5094565404) which includes the fix. Let me know if this solves the issue for you as well.

BR,
Philipp

**Comment by BHMath** [comment] 2023-05-30 07:54
Nicely done ! it seems to be working indeed. Thanks !

**Comment by Fruchtzwerg94** [comment] 2023-05-30 16:48
Thanks for your response. The change will be part of the next release.

**Closed by Fruchtzwerg94** 2023-05-30 16:48 UTC
Labels: bug
